version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    overwrite: true
file_exists_behavior: OVERWRITE
branch_config:
    wip\/.*: ~ 
    main:
        deploymentGroupName: test-Aakash-DG
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::688567295390:role/test-codedeploy-role
